var jsonData = [    { id: 1, parentId: 0, code: "platform", name: "平台配置中心", checked: true },
    { id: 2, parentId: 0, code: "pay", name: "支付中心", checked: null },
    { id: 3, parentId: 0, code: "product", name: "产品中心", checked: true },
    { id: 1000, parentId: 1, code: "platform-organization", name: "组织架构", checked: true },
    { id: 1001, parentId: 1, code: "platform-scenic", name: "景区管理", checked: true },
    { id: 1002, parentId: 2, code: "pay-trade", name: "资金账户管理", checked: null },
    { id: 1003, parentId: 3, code: "sale-param", name: "销售参数配置", checked: true },
    { id: 6000, parentId: 1000, code: "platform-organization-merchant", name: "商家管理", checked: true },
    { id: 6001, parentId: 6000, code: "platform-organization-merchant-save", name: "商家管理添加", checked: null },
    { id: 6002, parentId: 6000, code: "platform-organization-merchant-update", name: "商家管理修改", checked:true },
    { id: 6003, parentId: 6000, code: "platform-organization-merchant-disable", name: "商家管理禁用", checked:true },
    { id: 6004, parentId: 6000, code: "platform-organization-merchant-menu-allot", name: "商家管理权限分配", checked:true },
    { id: 6005, parentId: 1000, code: "platform-organization-sub-merchant", name: "企业管理", checked: true },
    { id: 6006, parentId: 6005, code: "platform-organization-sub-merchant-save", name: "企业管理添加", checked:true },
    { id: 6007, parentId: 6005, code: "platform-organization-sub-merchant-update", name: "企业管理修改", checked:true },
    { id: 6008, parentId: 6005, code: "platform-organization-sub-merchant-disable", name: "企业管理禁用", checked:true },
    { id: 6009, parentId: 1000, code: "platform-organization-dept", name: "部门管理", checked: true },
    { id: 6010, parentId: 6009, code: "platform-organization-dept-save", name: "部门管理添加", checked: true },
    { id: 6011, parentId: 6009, code: "platform-organization-dept-update", name: "部门管理修改", checked: true },
    { id: 6012, parentId: 6009, code: "platform-organization-dept-disable", name: "部门管理禁用", checked: true },
    { id: 6013, parentId: 1000, code: "platform-organization-role", name: "角色管理", checked: true },
    { id: 6014, parentId: 6013, code: "platform-organization-role-save", name: "角色管理添加", checked: true },
    { id: 6015, parentId: 6013, code: "platform-organization-role-update", name: "角色管理修改", checked: true },
    { id: 6016, parentId: 6013, code: "platform-organization-role-disable", name: "角色管理禁用", checked: true },
    { id: 6017, parentId: 6013, code: "platform-organization-role-menu-allot", name: "角色管理权限分配", checked:true },
    { id: 6018, parentId: 6013, code: "platform-organization-role-employee-allot", name: "角色管理员工分配", checked:true },
    { id: 6019, parentId: 6013, code: "platform-organization-role-merchant-allot", name: "角色管理商家分配", checked:true },
    { id: 6020, parentId: 1000, code: "platform-organization-employee", name: "员工管理", checked: true },
    { id: 6021, parentId: 6020, code: "platform-organization-employee-save", name: "员工管理添加", checked: true },
    { id: 6022, parentId: 6020, code: "platform-organization-employee-update", name: "员工管理修改", checked:true },
    { id: 6023, parentId: 6020, code: "platform-organization-employee-disable", name: "员工管理禁用", checked:true },
    { id: 6024, parentId: 6020, code: "platform-organization-employee-menu-allot", name: "员工管理权限分配", checked:true },
    { id: 6025, parentId: 1001, code: "platform-scenic-terminal-list", name: "设备管理", checked: true },
    { id: 6027, parentId: 6025, code: "platform-scenic-terminal-save", name: "设备管理添加", checked: true },
    { id: 6028, parentId: 6025, code: "platform-scenic-terminal-disable", name: "设备管理禁用", checked: true },
    { id: 6029, parentId: 6025, code: "platform-scenic-terminal-update", name: "设备管理编辑", checked: true },
    { id: 6030, parentId: 1001, code: "platform-scenic-station-list", name: "站点管理", checked: true },
    { id: 6032, parentId: 6030, code: "platform-scenic-station-save", name: "站点管理添加", checked: true },
    { id: 6033, parentId: 6030, code: "platform-scenic-station-update", name: "站点管理修改", checked: true },
    { id: 6034, parentId: 6030, code: "platform-scenic-station-disable", name: "站点管理禁用", checked: true },
    { id: 6035, parentId: 1001, code: "platform-scenic-scenic-list", name: "景点项目", checked: true },
    { id: 6036, parentId: 6035, code: "platform-scenic-scenic-save", name: "景点项目添加", checked: true },
    { id: 6037, parentId: 6035, code: "platform-scenic-scenic-update", name: "景点项目修改", checked: true },
    { id: 6038, parentId: 6035, code: "platform-scenic-scenic-disable", name: "景点项目禁用", checked: true },
    { id: 6040, parentId: 1002, code: "pay-trade-account", name: "资金账户管理", checked: null },
    { id: 6041, parentId: 6040, code: "pay-trade-account-save", name: "资金账户管理添加", checked: null },
    { id: 6042, parentId: 6040, code: "pay-trade-account-update", name: "资金账户管理修改", checked: null },
    { id: 6043, parentId: 6040, code: "pay-trade-account-disable", name: "资金账户管理禁用", checked: null },
    { id: 6044, parentId: 6040, code: "pay-trade-account-config", name: "资金账户管理支付配置", checked: null },
    { id: 6045, parentId: 6040, code: "pay-trade-sub-account", name: "资金账户管理分配配置", checked: null },
    { id: 6046, parentId: 1003, code: "salerule-saleparam-use-date-plan", name: "有效期方案", checked: true },
    { id: 6047, parentId: 6046, code: "salerule-saleparam-use-date-plan-save", name: "有效期方案添加", checked:true },
    { id: 6048, parentId: 6046, code: "salerule-saleparam-use-date-plan-update", name: "有效期方案修改", checked:true },
    { id: 6049, parentId: 6046, code: "salerule-saleparam-use-date-plan-disable", name: "有效期方案禁用", checked:true },
    { id: 6051, parentId: 1003, code: "salerule-saleparam-price-date-plan-list", name: "价格日期方案", checked:true },
    { id: 6052, parentId: 6051, code: "salerule-saleparam-price-date-plan-save", name: "价格日期方案添加", checked:true },
    { id: 6053, parentId: 6051, code: "salerule-saleparam-price-date-plan-update", name: "价格日期方案修改", checked:true },
    { id: 6055, parentId: 6051, code: "salerule-saleparam-price-date-plan-disable", name: "价格日期方案禁用", checked:true },
    { id: 6056, parentId: 1003, code: "salerule-saleparam-event", name: "事件类型", checked: true },
    { id: 6057, parentId: 6056, code: "salerule-saleparam-event-save", name: "事件类型添加", checked: true },
    { id: 6058, parentId: 6056, code: "salerule-saleparam-event-update", name: "事件类型修改", checked: true },
    { id: 6059, parentId: 6056, code: "salerule-saleparam-event-disable", name: "事件类型禁用", checked: true },
    { id: 6060, parentId: 1003, code: "salerule-saleparam-settle-way", name: "结算方式", checked: true },
    { id: 6061, parentId: 6060, code: "salerule-saleparam-settle-way-save", name: "结算方式添加", checked: true },
    { id: 6062, parentId: 6060, code: "salerule-saleparam-settle-way-update", name: "结算方式修改", checked: true },
    { id: 6063, parentId: 6060, code: "salerule-saleparam-settle-way-disable", name: "结算方式禁用", checked:true },
    { id: 6064, parentId: 6045, code: "pay-trade-sub-account-save", name: "添加资金账户分账账户", checked: null },
    { id: 6065, parentId: 6045, code: "pay-trade-sub-account-update", name: "修改资金账户分账账户", checked: null },
    { id: 6066, parentId: 6045, code: "pay-trade-sub-account-disable", name: "禁用资金账户分账账户", checked: null },
    { id: 6067, parentId: 1003, code: "salerule-saleparam-business-list", name: "业务类型", checked: true },
    { id: 6068, parentId: 6067, code: "salerule-saleparam-business-save", name: "业务类型添加", checked: true },
    { id: 6069, parentId: 6067, code: "salerule-saleparam-business-update", name: "业务类型修改", checked: true },
    { id: 6070, parentId: 6067, code: "salerule-saleparam-business-disable", name: "业务类型禁用", checked: true },
    { id: 6071, parentId: 6067, code: "salerule-saleparam-business-extra-list", name: "附加登记信息", checked:true },
    { id: 6072, parentId: 6071, code: "salerule-saleparam-business-extra-save", name: "附加登记信息添加", checked:true },
    { id: 6073, parentId: 6071, code: "salerule-saleparam-business-extra-update", name: "附加登记信息修改", checked:true },
    { id: 6074, parentId: 6071, code: "salerule-saleparam-business-extra-remove", name: "附加登记信息删除", checked:true },
    { id: 6075, parentId: 6067, code: "salerule-saleparam-business-settle-way-list", name: "分配结算方式", checked:true },
    { id: 6076, parentId: 6075, code: "salerule-saleparam-business-settle-way-save", name: "分配结算方式添加", checked:true },
    { id: 6077, parentId: 6075, code: "salerule-saleparam-business-settle-way-update", name: "分配结算方式修改", checked:true },
    { id: 6078, parentId: 6075, code: "salerule-saleparam-business-settle-way-disable", name: "分配结算方式禁用", checked:true },
    { id: 6079, parentId: 1003, code: "salerule-saleparam-id-card-plan-list", name: "身份证画像方案", checked:true },
    { id: 6080, parentId: 6079, code: "salerule-saleparam-id-card-plan-save", name: "身份证画像方案添加", checked:true },
    { id: 6081, parentId: 6079, code: "salerule-saleparam-id-card-plan-update", name: "身份证画像方案修改", checked:true },
    { id: 6082, parentId: 6079, code: "salerule-saleparam-id-card-plan-disable", name: "身份证画像方案禁用", checked:true },
    { id: 6083, parentId: 6020, code: "platform-organization-employee-role-allot", name: "员工管理角色分配", checked:true }]